import { StyleSheet } from "react-native";

export default StyleSheet.create({

    container: {
        backgroundColor: '#d3d2d3',
        flex: 1,
    },
    flashcardContainer: {
        flex: 1,
        backgroundColor: '#d6d3d8',
        justifyContent: 'center',
    },
    multipleContainer: {
        flex: 1,
        backgroundColor: '#d6d3d8',
        justifyContent: 'center',
        alignItems: "center"
    },
    gameOverContainer: {
        width: "75%",
        padding: 20,
        borderRadius: 10,
        borderColor: "#9051a5",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 20,
        boxShadow: "10px 10px 17px -12px rgba(0,0,0,0.75)",
        elevation: 8,
    },
    input: {
        height: 50,
        borderColor: '#686868',
        borderWidth: 2,
        marginTop: 10,
        width: '75%',
        borderRadius: 8,
        paddingHorizontal: 10,
        backgroundColor: '#f4f3f3',
        color: '#333',
        boxShadow: "10px 10px 17px -17px rgba(74, 73, 73, 0.75)",
    },
    deck: {
        padding: 15,
        marginVertical: 12,
        marginHorizontal: 12,
        borderRadius: 10,
        boxShadow: "10px 10px 17px -12px rgba(0,0,0,0.75)",
        elevation: 8,
        height: 160,
        width: "75%",
        alignSelf: "center",
        justifyContent: "center",
        alignItems: "center",
    },
    deckModal: {
        width: '85%',
        height: 310,
        borderColor:"#5c5c5c",
        borderWidth:1,
        borderRadius: 15,
        elevation: 5,
        boxShadow: "10px 10px 17px -12px rgba(0, 0, 0, 0.75)",
    },
    modalBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(81, 60, 87, 0.6)',
    },
    modalHeaderBox: {
        width: "100%",
        backgroundColor: "#994cd9",
        paddingVertical: 12,
        paddingHorizontal: 30,
        height:55,
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    modalHeaderText: {
        color: "white",
        fontSize: 18,
        fontWeight: "600",
    },
    modalClose: {
        position: "absolute",
        right: 5,
        top: 3,
    },
    headerStyle: {
        fontSize: 20,
        marginBottom: 10,
        fontWeight: 500,
        alignSelf: "center",
        textAlign:"center"

    },
    cardTitle: {
        position: "absolute",
        textAlign: "center",
        fontSize: 20,
        fontWeight: 500,
        width:"70%"

    },
    deckDescription: {
        fontSize: 15,
        marginTop: 10,
        textAlign: 'center',
        paddingHorizontal:20,
    },
     notifyText: {
        flex: 1,
        alignItems: "center",
        textAlign: "center",
        fontSize: 15,
        paddingTop: 300,
    },
    centerLine: {
        position: "absolute",
        top: 0,
        bottom: 0,
        width: 2,
        backgroundColor: "rgba(255,255,255,0.4)",
        left: "15%",
    },
    centerToLeftLine: {
        position: "absolute",
        width: "90%",
        height: 2,
        backgroundColor: "rgba(255,255,255,0.4)",
    },
    gameOverLine: {
        width: "80%",
        height: 2,
        backgroundColor: "rgba(255,255,255,0.5)",
        marginTop: 8,
        marginBottom: 20,
        alignSelf: "center",
    },
    addButton: {
        position: 'absolute',
        bottom: 15,
        right: 15,
        borderWidth: 3,
        borderColor: "#424143",
    },
    defaultButton: {
        width: "35%",
        marginTop:15,
        backgroundColor: '#a662c7',
        borderWidth:2,
        borderRadius: 10,
        elevation: 5,
        borderColor: "#73468a",
    },
    saveButton: {
        backgroundColor: "#b56cda",
        width: "75%",
        marginTop: 25,
        borderRadius: 5,
        borderWidth: 2.5,
        borderColor: "#605f5f",
        boxShadow: "10px 10px 17px -12px rgba(73, 38, 83, 0.75)",

    },
    choiceButton: {
        padding: 12,
        borderRadius: 10,
        borderColor: "#9059ab",
        borderWidth: 2,
        marginVertical: 6,
        width: "70%",
        backgroundColor: "#c176e7",
    },
    choiceText: {
        color: "black",
        fontSize: 16,
        fontWeight: 500,
        textAlign:"center",
        paddingHorizontal:30,
    },
    choiceRow:{ 
        width: "100%", 
        flexDirection: "row", 
        alignItems: "center", 
        justifyContent: "center", 
        position: "relative",
    },
    options: {
        borderWidth: 2,
        borderColor: "#918888",
        borderRadius: 6,
        marginHorizontal: 8,
        marginVertical: 3,
        backgroundColor: "#caa1f9",
    },

})